#pragma once

#include "ObjectScript.h"
#include <Refureku/Generated/LuaScript.rfkh.h>

const std::string luaScriptTemplate = 
	"-- This code was automatically generated by CrystalEngine.\n\n"
	"function Start()\n"
		"\t-- Content --\n"
	"end\n\n"
	"function LateStart()\n"
		"\t-- Content --\n"
	"end\n\n"
	"function Update()\n"
		"\t-- Content --\n"
	"end\n\n"
	"function LateUpdate()\n"
		"\t-- Content --\n"
	"end\n";

namespace sol {
	class state;
}

namespace Scripts NAMESPACE()
{
	struct STRUCT() LuaScript : ObjectScript
	{
	private:
		std::string name;
		sol::state* state;

	public:
		METHOD(rfk::Instantiator) static rfk::UniquePtr<LuaScript> customInstantiator(const std::string& filename) {
			return std::make_unique<LuaScript>(filename);
		}
		
		LuaScript(std::string _name);
		~LuaScript() override = default;

		METHOD() static std::string CreateLuaFile(const std::string& fileName);
		
		METHOD() void Start() override;
		METHOD() void LateStart() override;
		METHOD() void Update() override;
		METHOD() void LateUpdate() override;
		METHOD() void SetValues();

		METHOD() sol::state* GetState() const { return state; }
		METHOD() std::string GetName() const { return name; }

		Scripts_LuaScript_GENERATED
	};
}
File_LuaScript_GENERATED